name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@phicomm-n1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        ls
        pwd
        free -g
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/*
        sudo swapoff /swapfile
        sudo rm -f /swapfile
        sudo -E apt-get -qq install gcc make autoconf pkg-config git bc bison flex libelf-dev libssl-dev libncurses5-dev dialog aria2 pv
        sudo -E apt-get -qq update
        sudo -E apt-get -qq clean
        sudo sh compile.sh BOARD=aml-g12 BRANCH=default RELEASE=bionic BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no EXTERNAL=no
